const GETALLUSERS_SUCCESS = 'GETALLUSERS_SUCCESS';
const GETALLUSERS_FAILURE = 'GETALLUSERS_FAILURE';
const CHANGECURRENTCHAT = 'CHANGECURRENTCHAT';
const SOCKETDISCONNECT = 'SOCKETDISCONNECT';
const NEWSOCKET = 'NEWSOCKET';
const SETONLINEUSERS = 'SETONLINEUSERS';

export { GETALLUSERS_SUCCESS, GETALLUSERS_FAILURE, NEWSOCKET, CHANGECURRENTCHAT, SOCKETDISCONNECT, SETONLINEUSERS };
