const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';
const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
const NAMECHANGE_SUCCESS = 'NAMECHANGE_SUCCESS';
const NAMECHANGE_FAILURE = 'NAMECHANGE_FAILURE';
const LOGOUT = 'LOGOUT';

const ADDCONTACT_SUCCESS = 'ADDCONTACT_SUCCESS';
const ADDCONTACT_FAILURE = 'ADDCONTACT_FAILURE';
const REMOVECONTACT_SUCCESS = 'REMOVECONTACT_SUCCESS';
const REMOVECONTACT_FAILURE = 'REMOVECONTACT_FAILURE';

const NEWCHAT = 'NEWCHAT';
const NEWCHATNAME = 'NEWCHATNAME';
const NEWMESSAGEINCHAT = 'NEWMESSAGEINCHAT';
const USERLEFTCHAT = 'USERLEFTCHAT';
const TYPINGMESSAGE = 'TYPINGMESSAGE';
const STOPPEDTYPING = 'STOPPEDTYPING';
const REMOVECHAT = 'REMOVECHAT';

export {
	LOGIN_SUCCESS,
	LOGIN_FAILURE,
	SIGNUP_SUCCESS,
	SIGNUP_FAILURE,
	NAMECHANGE_SUCCESS,
	NAMECHANGE_FAILURE,
	LOGOUT,
	ADDCONTACT_SUCCESS,
	ADDCONTACT_FAILURE,
	REMOVECONTACT_SUCCESS,
	REMOVECONTACT_FAILURE,
	NEWMESSAGEINCHAT,
	NEWCHAT,
	NEWCHATNAME,
	TYPINGMESSAGE,
	STOPPEDTYPING,
	USERLEFTCHAT,
	REMOVECHAT,
};
